#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh
/home/peter/bin/set_x.sh &
setxkbmap pl &
xbindkeys &
picom &
nitrogen --set-scaled --save --restore &
mpd &
dunst &
udiskie &
# xsetroot -solid "#000000" &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          26

bspc config split_ratio          0.59
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

(ps x | grep bspswallow | grep -v grep) || bspswallow &

